name: llamastack-pg
instances: 1
imageName: ""
storage:
  size: 10Gi
  storageClass: ""
database: llamastack
owner: llamastack
resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: "1"
    memory: 1Gi
