FROM registry.access.redhat.com/ubi9/python-312:latest

USER 0
WORKDIR /opt/app-root/src
COPY requirements.txt /opt/app-root/src/requirements.txt
RUN pip install --no-cache-dir -r requirements.txt
COPY src /opt/app-root/src/src
ENV PYTHONPATH=/opt/app-root/src/src
USER 1001
EXPOSE 8080
CMD ["python", "-m", "uvicorn", "orders.api:app", "--host", "0.0.0.0", "--port", "8080"]
