apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
patches:
  - path: delete-postgres-deploy.yaml
  - path: delete-postgres-svc.yaml
  - path: delete-mongo-deploy.yaml
  - path: delete-mongo-svc.yaml
  - path: delete-librechat-deploy.yaml
  - path: delete-librechat-svc.yaml
  - path: delete-librechat-route.yaml
  - path: delete-librechat-config.yaml
  - target:
      kind: ConfigMap
      name: demo-pipeline
    patch: |-
      - op: replace
        path: /data/MAAS_BASE_URL
        value: https://maas.apps.CHANGE_ME.example.com/ai-models/granite-3-0-8b-instruct
  - target:
      kind: LlamaStackDistribution
      name: llamastack
    patch: |-
      - op: replace
        path: /spec/server/containerSpec/env/0/value
        value: https://maas.apps.CHANGE_ME.example.com/ai-models/granite-3-0-8b-instruct/v1
      - op: replace
        path: /spec/server/containerSpec/env/4/value
        value: llamastack-pg-rw
      - op: replace
        path: /spec/server/containerSpec/env/7
        value:
          name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: llamastack-pg-app
              key: username
      - op: replace
        path: /spec/server/containerSpec/env/8
        value:
          name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: llamastack-pg-app
              key: password
