apiVersion: v2
name: demo-operators
description: OLM Subscriptions and DSC patch to enable Llama Stack, CloudNativePG and MongoDB Community on OpenShift.
type: application
version: 0.1.0
appVersion: "0.1.0"
keywords:
  - rhoai
  - llamastack
  - cnpg
  - mongodb
