{{- if and .Values.llamastack.enabled (eq .Values.llamastack.mode "community") }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.llamastack.namespace }}
  labels:
    app.kubernetes.io/part-of: rhoai-granite-code-demo
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: llama-stack
  namespace: {{ .Values.llamastack.namespace }}
spec: {}
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: llama-stack-k8s-operator
  namespace: {{ .Values.llamastack.namespace }}
spec:
  channel: {{ .Values.llamastack.channel }}
  installPlanApproval: {{ .Values.llamastack.installPlanApproval }}
  name: llama-stack-k8s-operator
  source: {{ .Values.llamastack.catalog }}
  sourceNamespace: {{ .Values.llamastack.catalogNamespace }}
{{- end }}
